const PRIMARY = '#e1d2ba';
const TEXT_COLOR = '#141312'
const BLACK_BUTTON_PRIMARY = '#141312'
const BLACK_BUTTON_SECONDARY = '#2d2c2a'
const RED_BUTTON_PRIMARY = '#e50642'
const RED_BUTTON_SECONDARY = '#ea2056'
const GREEN_BUTTON_PRIMARY = '#13d8b1' 
const GREEN_BUTTON_SECONDARY = '#13d8b1' 

export { PRIMARY, 
        TEXT_COLOR, 
        BLACK_BUTTON_PRIMARY, 
        BLACK_BUTTON_SECONDARY, 
        RED_BUTTON_PRIMARY, 
        RED_BUTTON_SECONDARY, 
        GREEN_BUTTON_PRIMARY,
        GREEN_BUTTON_SECONDARY  
};