const PRIMARY = '#e1d2ba';
const TEXT_COLOR = '#141312'
const BLACK_BUTTON_PRIMARY = '#141312'
const BLACK_BUTTON_SECONDARY = '#2d2c2a'

export { PRIMARY, TEXT_COLOR, BLACK_BUTTON_PRIMARY, BLACK_BUTTON_SECONDARY };